version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    
  server_medis:
    build: Server
    restart: always
    container_name: server_medis
    image: medis_server
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=10&retry_delay=10'

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./Web:/usr/share/nginx/html


  